//***************************************************************************
//  NARS2000 -- Syntax Object Header
//***************************************************************************

/***************************************************************************
    NARS2000 -- An Experimental APL Interpreter
    Copyright (C) 2006-2016 Sudley Place Software

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
***************************************************************************/


// DO NOT EDIT THIS FILE
// It is automatically generated by the APL function <synobj>
//   in J:\workspaces\2by2.ws.nars.  Instead, edit and run the APL function.

#ifdef DEFINE_VARS
  #define EXTERN
#else
  #define EXTERN extern
#endif

// Syntax Objects enum
typedef enum tagSO_ENUM
{
	soUNK = 0, 			// 00:  Unknown                                                
	soA      , 			// 01:  Array                                                  
	soMF     , 			// 02:  Monadic (primitive, user-defined, train, etc.) function
	soF      , 			// 03:  Ambivalent function                                    
	soNF     , 			// 04:  Niladic function                                       
	soMOP    , 			// 05:  Monadic operator                                       
	soDOP    , 			// 06:  Dyadic operator                                        
	soMOPN   , 			// 07:  Monadic operator, niladic derived function             
	soDOPN   , 			// 08:  Dyadic operator, ...                                   
	soIDX    , 			// 09:  Indexing []                                            
	soSP     , 			// 0A:  Assignment/Sink                                        
	soGO     , 			// 0B:  Goto                                                   
	soJ      , 			// 0C:  Jot                                                    
	soJD     , 			// 0D:  Jot Dot                                                
	soLP     , 			// 0E:  Left paren                                             
	soRP     , 			// 0F:  Right paren                                            
	soLBK    , 			// 10:  Left bracket                                           
	soSEMI   , 			// 11:  Semicolon                                              
	soRBK    , 			// 12:  Right bracket                                          
	soHY     , 			// 13:  Hybrid:  /\ and barred forms                           
	soSPA    , 			// 14:  {is} A                                                 
	soSPF    , 			// 15:  {is} F                                                 
	soSPM    , 			// 16:  {is} MOP                                               
	soSPD    , 			// 17:  {is} DOP                                               
	soSPHY   , 			// 18:  {is} HY                                                
	soSPNF   , 			// 19:  {is} NF                                                
	soSPFR   , 			// 1A:  {is} FR                                                
	soSPMR   , 			// 1B:  {is} MR                                                
	soSPDR   , 			// 1C:  {is} DR                                                
	soSPHR   , 			// 1D:  {is} HR                                                
	soSPMN   , 			// 1E:  {is} MOPN                                              
	soSPDN   , 			// 1F:  {is} DOPN                                              
	soSPAK   , 			// 20:  {is} ARBK                                              
	soFR     , 			// 21:  F)    - Trains                                         
	soMR     , 			// 22:  MOP)  - ...                                            
	soDR     , 			// 23:  DOP)  - ...                                            
	soHR     , 			// 24:  HY)   - ...                                            
	soFFR    , 			// 25:  F F)  - ...                                            
	soAFR    , 			// 26:  A F)  - ...                                            
	soHFR    , 			// 27:  H F)  - ...                                            
	soNAM    , 			// 28:  Name                                                   
	soSA     , 			// 29:  Strand                                                 
	soLBC    , 			// 2A:  Left brace                                             
	soRBC    , 			// 2B:  Right brace                                            
	soCSF    , 			// 2C:  :FOR/:FORLCL                                           
	soCSI    , 			// 2D:  :IN                                                    
	soCSIA   , 			// 2E:  :IN A                                                  
	soCSFN   , 			// 2F:  :FOR NAM/:FORLCL NAM                                   
	soCSEF   , 			// 30:  :ENDFOR/:ENDFORLCL                                     
	soCS0    , 			// 31:  CS Niladic                                             
	soCS1    , 			// 32:  CS Monadic                                             
	soSOS    , 			// 33:  Start of stmt                                          
	soAFOG   , 			// 34:  AFO Guard                                              
	soAFOR   , 			// 35:  AFO Return                                             
	soSYSN   , 			// 36:  System Namespace                                       
	soARBK   , 			// 37:  A RBR                                                  
	soSRBK   , 			// 38:  ; RBR/RBR2                                             
	soIO     , 			// 39:  I/O                                                    
	soNR     , 			// 3A:  NAM)                                                   
	soNNR    , 			// 3B:  NAM NAM)                                               
	soLNR    , 			// 3C:  (NAM NAM)                                              
	soISPA   , 			// 3D:  IDX SPA                                                
	soNDX    , 			// 3E:  NAM IDX F MOP SPA => NAM NDX F MOP SPA & left shift    
	soSYNR   , 			// 3F:  SYNTAX ERROR                                           
	soVALR   , 			// 40:  VALUE ERROR                                            
	soNVAL   , 			// 41:  No Value                                               
	soEOS    , 			// 42:  *MUST* be the highest numbered entry                   
	soNONE = 999,		//999:  Filler for no entry
} SO_ENUM, *LPSO_ENUM;

#define soLAST		soEOS

#ifdef DEBUG
// Syntax Object Names
EXTERN
LPWCHAR soNames[]
#ifdef DEFINE_VALUES
= {
	L"UNK" ,			// 00:  Unknown                                                
	L"A"   ,			// 01:  Array                                                  
	L"MF"  ,			// 02:  Monadic (primitive, user-defined, train, etc.) function
	L"F"   ,			// 03:  Ambivalent function                                    
	L"NF"  ,			// 04:  Niladic function                                       
	L"MOP" ,			// 05:  Monadic operator                                       
	L"DOP" ,			// 06:  Dyadic operator                                        
	L"MOPN",			// 07:  Monadic operator, niladic derived function             
	L"DOPN",			// 08:  Dyadic operator, ...                                   
	L"IDX" ,			// 09:  Indexing []                                            
	L"SP"  ,			// 0A:  Assignment/Sink                                        
	L"GO"  ,			// 0B:  Goto                                                   
	L"J"   ,			// 0C:  Jot                                                    
	L"JD"  ,			// 0D:  Jot Dot                                                
	L"("   ,			// 0E:  Left paren                                             
	L")"   ,			// 0F:  Right paren                                            
	L"["   ,			// 10:  Left bracket                                           
	L";"   ,			// 11:  Semicolon                                              
	L"]"   ,			// 12:  Right bracket                                          
	L"HY"  ,			// 13:  Hybrid:  /\ and barred forms                           
	L"SPA" ,			// 14:  {is} A                                                 
	L"SPF" ,			// 15:  {is} F                                                 
	L"SPM" ,			// 16:  {is} MOP                                               
	L"SPD" ,			// 17:  {is} DOP                                               
	L"SPHY",			// 18:  {is} HY                                                
	L"SPNF",			// 19:  {is} NF                                                
	L"SPFR",			// 1A:  {is} FR                                                
	L"SPMR",			// 1B:  {is} MR                                                
	L"SPDR",			// 1C:  {is} DR                                                
	L"SPHR",			// 1D:  {is} HR                                                
	L"SPMN",			// 1E:  {is} MOPN                                              
	L"SPDN",			// 1F:  {is} DOPN                                              
	L"SPAK",			// 20:  {is} ARBK                                              
	L"FR"  ,			// 21:  F)    - Trains                                         
	L"MR"  ,			// 22:  MOP)  - ...                                            
	L"DR"  ,			// 23:  DOP)  - ...                                            
	L"HR"  ,			// 24:  HY)   - ...                                            
	L"FFR" ,			// 25:  F F)  - ...                                            
	L"AFR" ,			// 26:  A F)  - ...                                            
	L"HFR" ,			// 27:  H F)  - ...                                            
	L"NAM" ,			// 28:  Name                                                   
	L"SA"  ,			// 29:  Strand                                                 
	L"{"   ,			// 2A:  Left brace                                             
	L"}"   ,			// 2B:  Right brace                                            
	L"CSF" ,			// 2C:  :FOR/:FORLCL                                           
	L"CSI" ,			// 2D:  :IN                                                    
	L"CSIA",			// 2E:  :IN A                                                  
	L"CSFN",			// 2F:  :FOR NAM/:FORLCL NAM                                   
	L"CSEF",			// 30:  :ENDFOR/:ENDFORLCL                                     
	L"CS0" ,			// 31:  CS Niladic                                             
	L"CS1" ,			// 32:  CS Monadic                                             
	L"SOS" ,			// 33:  Start of stmt                                          
	L"AFOG",			// 34:  AFO Guard                                              
	L"AFOR",			// 35:  AFO Return                                             
	L"SYSN",			// 36:  System Namespace                                       
	L"ARBK",			// 37:  A RBR                                                  
	L"SRBK",			// 38:  ; RBR/RBR2                                             
	L"IO"  ,			// 39:  I/O                                                    
	L"NR"  ,			// 3A:  NAM)                                                   
	L"NNR" ,			// 3B:  NAM NAM)                                               
	L"LNR" ,			// 3C:  (NAM NAM)                                              
	L"ISPA",			// 3D:  IDX SPA                                                
	L"NDX" ,			// 3E:  NAM IDX F MOP SPA => NAM NDX F MOP SPA & left shift    
	L"SYNR",			// 3F:  SYNTAX ERROR                                           
	L"VALR",			// 40:  VALUE ERROR                                            
	L"NVAL",			// 41:  No Value                                               
	L"EOS" ,			// 42:  *MUST* be the highest numbered entry                   
  }
#endif
;
#endif

#undef  EXTERN

#define SONAMES_MAXLEN	5


//***************************************************************************
//  End of File: synobj.h
//***************************************************************************
