pref ("extensions.aplchars.charsenabled"        , true);
pref ("extensions.aplchars.customize"           , false);
pref ("extensions.aplchars.keyboardlayout"      , "NARS2000");
pref ("extensions.aplchars.fontsenabled"        , false);
pref ("extensions.aplchars.fontnameroot"        , "font.name.monospace.");
pref ("extensions.aplchars.fontnametype"        , "x-western");
pref ("extensions.aplchars.aplfontfamilyid"     , "SImPL");
pref ("extensions.aplchars.aplfontfamilyname"   , "SImPL");
pref ("extensions.aplchars.oldfontfamilyname"   , "Arial");
